version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:15211/xe
      SPRING_DATASOURCE_USERNAME: expenser_db
      SPRING_DATASOURCE_PASSWORD: expenser_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  oracle-db:
    image: container-registry.oracle.com/database/express:18.4.0-xe
    ports:
      - "15211:15211"
    environment:
      ORACLE_PWD: root
      ORACLE_SCRIPTS: /opt/oracle/scripts/startup
    volumes:
      - ./db/patch/10000001_initialDbSetup.sql:/opt/oracle/scripts/startup/init.sql