CREATE TABLE CHANGELOG_Expenser
   (	CHANGE_NUMBER NUMBER(*,0), 
	COMPLETE_DT TIMESTAMP (6) DEFAULT (CURRENT_TIMESTAMP) NOT NULL ENABLE, 
	APPLIED_BY VARCHAR2(100 BYTE) DEFAULT (USER) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(500 BYTE) NOT NULL ENABLE, 
    PRIMARY KEY (CHANGE_NUMBER));
