import { Col, Row } from "antd";
import { TreeNode } from "antd/lib/tree-select";
import icons from "./../assets/sprite.svg";

export const CategoryList = [
  {
    value: 10,
    title: "Food & Drinks",
    color: "#f44336",
    icon: "restaurant",
    identifier: "",
    parentvalue: null,
    selectable: false,
    children: [
      {
        customCategory: false,
        color: "#f44336",
        value: 1000,
        title: "Groceries",
        parentvalue: 10,
        identifier: "303890ea-a84d-4453-861a-169b2079849f",
        icon: "add_shopping_cart",
        children: [],
      },
      {
        title: "Restaurant, fast-food",
        color: "#f44336",
        icon: "fastfood",
        value: 1001,
        parentvalue: 10,
        customCategory: false,
      },
      {
        color: "#f44336",
        customCategory: false,
        value: 1002,
        title: "Bar, cafe",
        parentvalue: 10,
        icon: "glass2",
        children: [],
      },
      {
        color: "#f44336",
        customCategory: false,
        value: 1003,
        title: "Food & Drinks",
        parentvalue: 10,
        icon: "restaurant",
        children: [],
      },
    ],
  },
  {
    value: 20,
    title: "Shopping",
    color: "#4fC3F7",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        color: "#4fC3F7",
        customCategory: false,
        value: 2000,
        title: "Clothes & shoes",
        parentvalue: 20,
        icon: "t-shirt",
        children: [],
      },
      {
        title: "Jewels, accessories",
        color: "#4fC3F7",
        icon: "diamond",
        value: 2001,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Health and beauty",
        color: "#4fC3F7",
        icon: "add_shopping_cart",
        value: 2002,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Kids",
        color: "#4fC3F7",
        icon: "child_friendly",
        value: 2003,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Home, garden",
        color: "#4fC3F7",
        icon: "park",
        value: 2004,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Pets, animals",
        color: "#4fC3F7",
        icon: "pets",
        value: 2005,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Electronics, accessories",
        color: "#4fC3F7",
        icon: "monitor",
        value: 2006,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Gifts, joy",
        color: "#4fC3F7",
        icon: "redeem",
        value: 2007,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Stationery, tools",
        color: "#4fC3F7",
        icon: "create",
        value: 2008,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Free time",
        color: "#4fC3F7",
        icon: "hourglass_full",
        value: 2009,
        parentvalue: 20,
        customCategory: false,
      },
      {
        title: "Shopping",
        color: "#4fC3F7",
        icon: "shopping_bag",
        value: 2010,
        parentvalue: 20,
        customCategory: false,
      },
      {
        color: "#4fC3F7",
        customCategory: false,
        value: 2011,
        title: "Drug-store, chemist",
        parentvalue: 20,
        icon: "medical_services",
        children: [],
      },
    ],
  },
  {
    value: 30,
    title: "Housing",
    color: "#FFA726",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Rent",
        color: "#FFA726",
        icon: "shopping_bag",
        value: 3000,
        parentvalue: 30,
        customCategory: false,
      },
      {
        color: "#FFA726",
        customCategory: false,
        value: 3001,
        title: "Mortgage",
        parentvalue: 30,
        icon: "shopping_bag",
        children: [],
      },
      {
        customCategory: false,
        color: "#FFA726",
        value: 3002,
        title: "Energy, utilities",
        parentvalue: 30,
        icon: "shopping_bag",
        children: [],
      },
      {
        title: "Services",
        color: "#FFA726",
        icon: "shopping_bag",
        value: 3003,
        parentvalue: 30,
        customCategory: false,
      },
      {
        title: "Maintenance, repairs",
        color: "#FFA726",
        icon: "shopping_bag",
        value: 3004,
        parentvalue: 30,
        customCategory: false,
      },
      {
        title: "Housing",
        color: "#FFA726",
        icon: "shopping_bag",
        value: 3005,
        parentvalue: 30,
        customCategory: false,
      },
      {
        title: "Property insurance",
        color: "#FFA726",
        icon: "shopping_bag",
        value: 3010,
        parentvalue: 30,
        customCategory: false,
      },
    ],
  },
  {
    value: 40,
    title: "Transportation",
    color: "#78909C",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        customCategory: false,
        color: "#78909C",
        value: 4000,
        title: "Public transport",
        parentvalue: 40,
        icon: "shopping_bag",
        children: [],
      },
      {
        title: "Taxi",
        color: "#78909C",
        icon: "shopping_bag",
        value: 4001,
        parentvalue: 40,
        customCategory: false,
      },
      {
        color: "#78909C",
        customCategory: false,
        value: 4002,
        title: "Long distance",
        parentvalue: 40,
        icon: "shopping_bag",
        children: [],
      },
      {
        color: "#78909C",
        customCategory: false,
        value: 4003,
        title: "Business trips",
        parentvalue: 40,
        icon: "shopping_bag",
        children: [],
      },
      {
        color: "#78909C",
        customCategory: false,
        value: 4004,
        title: "Transportation",
        parentvalue: 40,
        icon: "shopping_bag",
        children: [],
      },
    ],
  },
  {
    value: 50,
    title: "Vehicle",
    color: "#AA00FF",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Fuel",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5000,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Parking",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5001,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Vehicle maintenance",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5002,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Rentals",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5003,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Vehicle",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5004,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Vehicle insurance",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 5010,
        parentvalue: 50,
        customCategory: false,
      },
      {
        title: "Leasing",
        color: "#AA00FF",
        icon: "shopping_bag",
        value: 8006,
        parentvalue: 50,
        customCategory: false,
      },
    ],
  },
  {
    value: 60,
    title: "Life & Entertainment",
    color: "#64DD17",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        customCategory: false,
        color: "#64DD17",
        value: 6000,
        title: "Health care, doctor",
        parentvalue: 60,
        icon: "shopping_bag",
        children: [],
      },
      {
        title: "Wellness, beauty",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6001,
        parentvalue: 60,
        customCategory: false,
      },
      {
        customCategory: false,
        color: "#64DD17",
        value: 6002,
        title: "Active sport, fitness",
        parentvalue: 60,
        icon: "shopping_bag",
        children: [],
      },
      {
        title: "Culture, sport events",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6003,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Life events",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6004,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Hobbies",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6005,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Education, development",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6006,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Books, audio, subscriptions",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6007,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "TV, Streaming",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6008,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Holvalueay, trips, hotels",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6009,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Charity, gifts",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6010,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Alcohol, tobacco",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6011,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Lottery, gambling",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6012,
        parentvalue: 60,
        customCategory: false,
      },
      {
        title: "Life & Entertainment",
        color: "#64DD17",
        icon: "shopping_bag",
        value: 6013,
        parentvalue: 60,
        customCategory: false,
      },
    ],
  },
  {
    value: 70,
    title: "Communication, PC",
    color: "#536DFE",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Phone, mobile phone",
        color: "#536DFE",
        icon: "shopping_bag",
        value: 7001,
        parentvalue: 70,
        customCategory: false,
      },
      {
        title: "Internet",
        color: "#536DFE",
        icon: "shopping_bag",
        value: 7002,
        parentvalue: 70,
        customCategory: false,
      },
      {
        title: "Software, apps, games",
        color: "#536DFE",
        icon: "shopping_bag",
        value: 7003,
        parentvalue: 70,
        customCategory: false,
      },
      {
        title: "Postal services",
        color: "#536DFE",
        icon: "shopping_bag",
        value: 7004,
        parentvalue: 70,
        customCategory: false,
      },
      {
        title: "Communication, PC",
        color: "#536DFE",
        icon: "shopping_bag",
        value: 7005,
        parentvalue: 70,
        customCategory: false,
      },
    ],
  },
  {
    value: 80,
    title: "Financial expenses",
    color: "#00BFA5",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Taxes",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8000,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Insurances",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8001,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Loan, interests",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8002,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Fines",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8003,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Advisory",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8004,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Charges, Fees",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8005,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Child Support",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8007,
        parentvalue: 80,
        customCategory: false,
      },
      {
        title: "Financial expenses",
        color: "#00BFA5",
        icon: "shopping_bag",
        value: 8008,
        parentvalue: 80,
        customCategory: false,
      },
    ],
  },
  {
    value: 90,
    title: "Investments",
    color: "#FF4081",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Realty",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9000,
        parentvalue: 90,
        customCategory: false,
      },
      {
        title: "Vehicles, chattels",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9001,
        parentvalue: 90,
        customCategory: false,
      },
      {
        title: "Financial investments",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9002,
        parentvalue: 90,
        customCategory: false,
      },
      {
        title: "Savings",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9003,
        parentvalue: 90,
        customCategory: false,
      },
      {
        title: "Collections",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9004,
        parentvalue: 90,
        customCategory: false,
      },
      {
        title: "Investments",
        color: "#FF4081",
        icon: "shopping_bag",
        value: 9005,
        parentvalue: 90,
        customCategory: false,
      },
    ],
  },
  {
    value: 100,
    title: "Income",
    color: "#FBC02D",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Wage, invoices",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10000,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Interests, divvalueends",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10001,
        parentvalue: 100,
        customCategory: false,
      },
      {
        color: "#FBC02D",
        customCategory: false,
        value: 10002,
        title: "Sale",
        parentvalue: 100,
        icon: "shopping_bag",
        children: [],
      },
      {
        title: "Rental income",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10003,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Dues & grants",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10004,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Lending, renting",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10005,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Checks, coupons",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10006,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Lottery, gambling",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10007,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Refunds (tax, purchase)",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10008,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Child Support",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10009,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Gifts",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10010,
        parentvalue: 100,
        customCategory: false,
      },
      {
        title: "Income",
        color: "#FBC02D",
        icon: "shopping_bag",
        value: 10011,
        parentvalue: 100,
        customCategory: false,
      },
    ],
  },
  {
    value: 110,
    title: "Others",
    color: "#9E9E9E",
    icon: "shopping_bag",
    parentvalue: null,
    selectable: false,
    children: [
      {
        title: "Others",
        color: "#9E9E9E",
        icon: "shopping_bag",
        value: 11000,
        parentvalue: 110,
        customCategory: false,
      },
      {
        title: "Missing",
        color: "#9E9E9E",
        icon: "shopping_bag",
        value: 11001,
        parentvalue: 110,
        customCategory: false,
      },
    ],
  },
];

export const getCategoryTreeNodes = (CategoryList) => {
  if (CategoryList && CategoryList.length > 0) {
    return CategoryList.map((c) => {
      return (
        <TreeNode
          value={c.identifier}
          title={
            <Row align="middle">
              <Col
                className="dot dot-icon"
                style={{
                  backgroundColor: c.color,
                  marginRight: "5px",
                }}>
                <svg className={`icon icon-${c.icon}`}>
                  <use href={`${icons}#icon-${c.icon}`}></use>
                </svg>
              </Col>
              <Col>
                <span>{c.title}</span>
              </Col>
            </Row>
          }
          selectable={c.selectable}
          key={c.value}>
          {getCategoryTreeNodes(c.children)}
        </TreeNode>
      );
    });
  }
};
